//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodMenu
    {
        public int FoodId { get; set; }
        public string FoodItem { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
